window.LyraWelcomeI18n = {
  "en-US": {
    title: "Welcome to Lyra OS", progressLabel: "Welcome progress", step: "Step {current} of {total}",
    projectEyebrow: "MEET YOUR SYSTEM", welcome: "Welcome to", projectLead: "A calm, dependable desktop built on openSUSE and refined as one coherent product.",
    featuresLabel: "Lyra OS principles", stableTitle: "Stable by design", stableText: "Conservative choices, integration tests and long-term support.", recoveryTitle: "Ready to recover", recoveryText: "Predictable updates backed by openSUSE recovery tools.",
    themeEyebrow: "SET THE MOOD", themeTitle: "Light or dark?", themeLead: "Lyra ships both. Pick the one you prefer — the wallpaper and apps follow along, and you can change it any time.", themeGroupLabel: "Appearance", themeLightTitle: "Light", themeDarkTitle: "Dark", themeApplied: "Appearance applied.", themeFailed: "The appearance could not be changed. You can set it later in Vega.", themeUnavailable: "This system does not expose the GNOME appearance settings.",
    profileEyebrow: "MAKE IT YOURS", profileTitle: "Choose your desktop", profileLead: "Lyra ships two desktop profiles. Pick one now — Vega can switch it again whenever you like.", profileGroupLabel: "Desktop profile", profileLyraTitle: "Lyra", profileLyraText: "GNOME plus the Lyra dock and menus.", profileVanillaTitle: "GNOME Vanilla", profileVanillaText: "The standard GNOME experience, unchanged.", profileApplied: "Profile applied.", profileFailed: "The profile could not be changed. You can set it later in Vega.", profileUnavailable: "The Lyra profile is unavailable on this system, so GNOME Vanilla is selected.",
    networkEyebrow: "GET CONNECTED", networkTitle: "Connect to Wi-Fi", networkLead: "An internet connection helps Lyra fetch updates and install applications. You can also continue offline.", networkChecking: "Checking your connection…", networkCheckingText: "This takes only a moment.", networkConnected: "You are connected", networkConnectedText: "Lyra is ready to access updates and online services.", networkOffline: "You are offline", networkOfflineText: "Open Wi-Fi settings to choose a network, or continue without connecting.", openWifi: "Open Wi-Fi settings", checkAgain: "Check again",
    vegaEyebrow: "YOUR CONTROL CENTER", vegaTitle: "Meet Vega", vegaLead: "Vega brings Lyra's settings and maintenance tools together in one clear place.", vegaCardTitle: "Configure Lyra with confidence", vegaCardText: "Review system options, hardware and software without searching through separate tools.", openVega: "Open Vega", vegaOpened: "Vega is opening.", vegaOpenFailed: "Vega could not be opened.",
    back: "Back", next: "Next", finish: "Start using Lyra"
  },
  "pt-BR": {
    title: "Boas-vindas ao Lyra OS", progressLabel: "Progresso das boas-vindas", step: "Etapa {current} de {total}",
    projectEyebrow: "CONHEÇA SEU SISTEMA", welcome: "Boas-vindas ao", projectLead: "Um desktop tranquilo e confiável, construído sobre o openSUSE e lapidado como um produto coerente.",
    featuresLabel: "Princípios do Lyra OS", stableTitle: "Estável por princípio", stableText: "Escolhas conservadoras, testes de integração e suporte de longo prazo.", recoveryTitle: "Pronto para recuperar", recoveryText: "Atualizações previsíveis apoiadas pelas ferramentas de recuperação do openSUSE.",
    themeEyebrow: "DEFINA O CLIMA", themeTitle: "Claro ou escuro?", themeLead: "O Lyra traz os dois. Escolha o que preferir — o papel de parede e os aplicativos acompanham, e você pode trocar quando quiser.", themeGroupLabel: "Aparência", themeLightTitle: "Claro", themeDarkTitle: "Escuro", themeApplied: "Aparência aplicada.", themeFailed: "Não foi possível alterar a aparência. Você pode defini-la depois no Vega.", themeUnavailable: "Este sistema não expõe as configurações de aparência do GNOME.",
    profileEyebrow: "DO SEU JEITO", profileTitle: "Escolha sua área de trabalho", profileLead: "O Lyra traz dois perfis de área de trabalho. Escolha um agora — o Vega permite trocar quando quiser.", profileGroupLabel: "Perfil da área de trabalho", profileLyraTitle: "Lyra", profileLyraText: "GNOME mais o Dock e os menus do Lyra.", profileVanillaTitle: "GNOME Vanilla", profileVanillaText: "A experiência padrão do GNOME, sem alterações.", profileApplied: "Perfil aplicado.", profileFailed: "Não foi possível alterar o perfil. Você pode defini-lo depois no Vega.", profileUnavailable: "O perfil Lyra não está disponível neste sistema, então o GNOME Vanilla fica selecionado.",
    networkEyebrow: "CONECTE-SE", networkTitle: "Conecte-se ao Wi-Fi", networkLead: "Uma conexão ajuda o Lyra a buscar atualizações e instalar aplicativos. Você também pode continuar offline.", networkChecking: "Verificando sua conexão…", networkCheckingText: "Isso leva apenas um instante.", networkConnected: "Você está conectado", networkConnectedText: "O Lyra está pronto para acessar atualizações e serviços online.", networkOffline: "Você está offline", networkOfflineText: "Abra as configurações de Wi-Fi para escolher uma rede ou continue sem conectar.", openWifi: "Abrir configurações de Wi-Fi", checkAgain: "Verificar novamente",
    vegaEyebrow: "SUA CENTRAL DE CONTROLE", vegaTitle: "Conheça o Vega", vegaLead: "O Vega reúne as configurações e ferramentas de manutenção do Lyra em um lugar claro.", vegaCardTitle: "Configure o Lyra com confiança", vegaCardText: "Veja opções do sistema, hardware e software sem procurar em ferramentas separadas.", openVega: "Abrir o Vega", vegaOpened: "O Vega está abrindo.", vegaOpenFailed: "Não foi possível abrir o Vega.",
    back: "Voltar", next: "Avançar", finish: "Começar a usar o Lyra"
  },
  "es-ES": {
    title: "Te damos la bienvenida a Lyra OS", progressLabel: "Progreso de bienvenida", step: "Paso {current} de {total}",
    projectEyebrow: "CONOCE TU SISTEMA", welcome: "Te damos la bienvenida a", projectLead: "Un escritorio tranquilo y confiable, construido sobre openSUSE y refinado como un producto coherente.",
    featuresLabel: "Principios de Lyra OS", stableTitle: "Estable por diseño", stableText: "Decisiones conservadoras, pruebas de integración y soporte a largo plazo.", recoveryTitle: "Listo para recuperarse", recoveryText: "Actualizaciones previsibles respaldadas por las herramientas de recuperación de openSUSE.",
    themeEyebrow: "DEFINE EL AMBIENTE", themeTitle: "¿Claro u oscuro?", themeLead: "Lyra incluye ambos. Elige el que prefieras: el fondo y las aplicaciones se adaptan, y puedes cambiarlo cuando quieras.", themeGroupLabel: "Apariencia", themeLightTitle: "Claro", themeDarkTitle: "Oscuro", themeApplied: "Apariencia aplicada.", themeFailed: "No se pudo cambiar la apariencia. Puedes definirla más tarde en Vega.", themeUnavailable: "Este sistema no expone la configuración de apariencia de GNOME.",
    profileEyebrow: "A TU MANERA", profileTitle: "Elige tu escritorio", profileLead: "Lyra incluye dos perfiles de escritorio. Elige uno ahora: Vega permite cambiarlo cuando quieras.", profileGroupLabel: "Perfil del escritorio", profileLyraTitle: "Lyra", profileLyraText: "GNOME más el dock y los menús de Lyra.", profileVanillaTitle: "GNOME Vanilla", profileVanillaText: "La experiencia estándar de GNOME, sin cambios.", profileApplied: "Perfil aplicado.", profileFailed: "No se pudo cambiar el perfil. Puedes definirlo más tarde en Vega.", profileUnavailable: "El perfil Lyra no está disponible en este sistema, así que se selecciona GNOME Vanilla.",
    networkEyebrow: "CONÉCTATE", networkTitle: "Conéctate al Wi-Fi", networkLead: "Una conexión ayuda a Lyra a obtener actualizaciones e instalar aplicaciones. También puedes continuar sin conexión.", networkChecking: "Comprobando tu conexión…", networkCheckingText: "Solo tarda un instante.", networkConnected: "Estás conectado", networkConnectedText: "Lyra está listo para acceder a actualizaciones y servicios en línea.", networkOffline: "Estás sin conexión", networkOfflineText: "Abre la configuración Wi-Fi para elegir una red o continúa sin conectarte.", openWifi: "Abrir configuración Wi-Fi", checkAgain: "Comprobar de nuevo",
    vegaEyebrow: "TU CENTRO DE CONTROL", vegaTitle: "Conoce Vega", vegaLead: "Vega reúne la configuración y las herramientas de mantenimiento de Lyra en un lugar claro.", vegaCardTitle: "Configura Lyra con confianza", vegaCardText: "Revisa las opciones del sistema, hardware y software sin buscar en herramientas separadas.", openVega: "Abrir Vega", vegaOpened: "Vega se está abriendo.", vegaOpenFailed: "No se pudo abrir Vega.",
    back: "Atrás", next: "Siguiente", finish: "Empezar a usar Lyra"
  }
};
